export const SET_DOUGH = "SET_DOUGH";
export const SET_SIZE = "SET_SIZE";
export const SET_SAUCE = "SET_SAUCE";
export const SET_NAME_PIZZA = "SET_NAME_PIZZA";
export const CHANGE_COUNT_INGREDIENT = "CHANGE_COUNT_INGREDIENT";
export const RESET_BUILDER = "RESET_BUILDER";
export const CHANGE_BUILDER = "CHANGE_BUILDER";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ORDER = "REMOVE_ORDER";
export const INCREMENT_ORDER = "INCREMENT_ORDER";
export const DECREMENT_ORDER = "DECREMENT_ORDER";
